#!/usr/bin/env python3
"""Build the in-app full-text search index from the source PDF.

For each protocol, concatenate the plain text of the PDF page(s) it maps to (the
same pages the app displays) into data/searchText.ts. The search bar matches the
user's query against this text in addition to protocol titles.

Note: a few protocol pages are image-only flowcharts (e.g. the tachycardia
algorithm) with no extractable text; those contribute little/no searchable body
text, but the protocol is still found by its title.

Requires PyMuPDF:  pip install pymupdf
Usage (from the project root):  python scripts/build_search_index.py
"""
import json
import os
import re
import sys

try:
    import fitz  # PyMuPDF
except ImportError:
    sys.exit("PyMuPDF is required:  pip install pymupdf")

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PDF = os.path.join(ROOT, "source", "Mulvane-EMS-Protocols.pdf")
PAGEMAP_TS = os.path.join(ROOT, "data", "pageMap.ts")
OUT = os.path.join(ROOT, "data", "searchText.ts")


def main():
    doc = fitz.open(PDF)
    page_text = {i + 1: doc[i].get_text() for i in range(doc.page_count)}

    # Parse protocol id -> [pages] out of the generated pageMap.ts so the search
    # text always covers exactly the pages the app shows.
    pm = open(PAGEMAP_TS, encoding="utf-8").read()
    pairs = re.findall(r'"([^"]+)":\s*\[([0-9,\s]*)\]', pm)

    out = {}
    for pid, nums in pairs:
        pages = [int(x) for x in nums.split(",") if x.strip()]
        text = " ".join(page_text.get(p, "") for p in pages)
        # Drop leading page-number tokens, collapse whitespace.
        text = re.sub(r"\s+", " ", text).strip()
        out[pid] = text

    lines = [
        "// AUTO-GENERATED by scripts/build_search_index.py. Do not edit by hand.",
        "// Per-protocol plain text from the source PDF, for offline full-text search.",
        "export const PROTOCOL_TEXT: Record<string, string> = {",
    ]
    for pid, text in out.items():
        lines.append(f"  {json.dumps(pid)}: {json.dumps(text)},")
    lines.append("};\n")
    open(OUT, "w", encoding="utf-8").write("\n".join(lines))

    total = sum(len(t) for t in out.values())
    empties = [k for k, v in out.items() if len(v) < 20]
    print(f"Wrote {OUT}: {len(out)} protocols, {total} chars of search text.")
    print(f"Protocols with little/no body text (image-only): {empties or 'none'}")


if __name__ == "__main__":
    main()
