#!/usr/bin/env python3
"""Render the source protocol PDF into bundled page images + lookup tables.

This is the reproducible pipeline behind the app's "official page image" content
(Option A). Run it whenever the source PDF changes.

It:
  1. Reads source/Mulvane-EMS-Protocols.pdf
  2. Maps each protocol to its PDF page range, using the per-protocol start pages
     in scripts/protocol_start_pages.json (derived from the official table of
     contents) and excluding section-divider pages (low text, no image).
  3. Renders every referenced page to assets/pages/page-NNN.jpg (150 DPI).
  4. Regenerates assets/pages/index.ts (page -> require map) and
     data/pageMap.ts  (protocol id -> page numbers).

Requires PyMuPDF:  pip install pymupdf
Usage (from the project root):  python scripts/render_pages.py
"""
import json
import os
import re
import sys

try:
    import fitz  # PyMuPDF
except ImportError:
    sys.exit("PyMuPDF is required:  pip install pymupdf")

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PDF = os.path.join(ROOT, "source", "Mulvane-EMS-Protocols.pdf")
STARTS = os.path.join(ROOT, "scripts", "protocol_start_pages.json")
PAGES_DIR = os.path.join(ROOT, "assets", "pages")
DPI = 150
JPEG_QUALITY = 78
BIG_IMAGE_PX = 20000  # min pixel area to count a page as "has a diagram"


def main():
    doc = fitz.open(PDF)
    n = doc.page_count
    starts = json.load(open(STARTS))

    # Per-page facts: char count and whether it carries a substantive image.
    chars, has_image = {}, {}
    for i in range(n):
        pg = doc[i]
        chars[i + 1] = len(pg.get_text().strip())
        big = False
        for im in pg.get_images(full=True):
            info = doc.extract_image(im[0])
            if info["width"] * info["height"] > BIG_IMAGE_PX:
                big = True
                break
        has_image[i + 1] = big

    start_set = set(starts.values())

    def is_divider(p):
        # Section dividers: little text, no diagram, and not a protocol start.
        return chars[p] < 60 and not has_image[p] and p not in start_set

    # Each protocol owns pages from its start up to (next distinct start - 1),
    # minus divider pages.
    uniq = sorted(set(starts.values()))

    def end_of(s):
        nxt = [u for u in uniq if u > s]
        return (nxt[0] - 1) if nxt else n

    pagemap = {}
    for pid, s in starts.items():
        pagemap[pid] = [
            p for p in range(s, end_of(s) + 1) if p == s or not is_divider(p)
        ]

    all_pages = sorted({p for v in pagemap.values() for p in v})

    # Render.
    os.makedirs(PAGES_DIR, exist_ok=True)
    for old in os.listdir(PAGES_DIR):
        if re.match(r"page-\d+\.jpg$", old):
            os.remove(os.path.join(PAGES_DIR, old))
    for p in all_pages:
        data = doc[p - 1].get_pixmap(dpi=DPI).tobytes(
            output="jpeg", jpg_quality=JPEG_QUALITY
        )
        open(os.path.join(PAGES_DIR, f"page-{p:03d}.jpg"), "wb").write(data)

    # Regenerate assets/pages/index.ts
    lines = [
        "// AUTO-GENERATED by scripts/render_pages.py. Do not edit by hand.",
        "// Maps a PDF page number to its bundled JPEG.",
        "export const PAGE_IMAGES: Record<number, any> = {",
    ]
    lines += [f"  {p}: require('./page-{p:03d}.jpg')," for p in all_pages]
    lines.append("};\n")
    open(os.path.join(PAGES_DIR, "index.ts"), "w").write("\n".join(lines))

    # Regenerate data/pageMap.ts
    lines = [
        "// AUTO-GENERATED by scripts/render_pages.py. Do not edit by hand.",
        "// Maps each protocol id to the PDF page(s) that contain it.",
        "export const PROTOCOL_PAGES: Record<string, number[]> = {",
    ]
    for pid in pagemap:
        arr = ",".join(str(x) for x in pagemap[pid])
        lines.append(f"  {json.dumps(pid)}: [{arr}],")
    lines.append("};\n")
    open(os.path.join(ROOT, "data", "pageMap.ts"), "w").write("\n".join(lines))

    print(
        f"Rendered {len(all_pages)} pages for {len(pagemap)} protocols. "
        f"Excluded dividers: {[p for p in range(1, n + 1) if is_divider(p)]}"
    )


if __name__ == "__main__":
    main()
